# Generated by Django 3.2.3 on 2021-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_core', '0002_influencer_insta_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
