# Generated by Django 3.2.3 on 2021-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_core', '0004_suborder_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='insta_followers',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='insta_following',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='insta_posts',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
