# Generated by Django 3.2.3 on 2021-05-14 09:30

from django.db import migrations, models
import site_content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Site/Banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('order_no', models.PositiveIntegerField(default=site_content.models.getIncreasingBannerOrder)),
            ],
        ),
    ]
